<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Scp457</AssemblyName>
    <RootNamespace>Scp457</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SL_REFERENCES)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="CommandSystem.Core">
      <HintPath>$(SL_REFERENCES)\CommandSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="LabAPI">
      <HintPath>$(SL_REFERENCES)\LabAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Mirror">
      <HintPath>$(SL_REFERENCES)\Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SL_REFERENCES)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

</Project>
